### ISSUE TITLE
SwingSet on xs

### ISSUE THREAD

**Issue by dckc** [Agoric/SwingSet#126]
_IOU more detail..._

Current status: 12 / 16 PASS - 4 FAIL. Best description is
https://github.com/dckc/SwingSet/tree/test-kernel-xs/test/test-kernel-xs 2784e5b

by comparison, on node, 500 / 500 tests pass

see also:
  - Agoric/SES#16 SES on xs
  - Moddable-OpenSource/moddable#257 debugging xs with VS Code

**Comment by dckc** [comment]
### Sharing import path specifiers

main issue: https://github.com/Agoric/agoric-sdk/issues/57

In trying to demonstrate that sharing import paths was no just difficult (https://github.com/Moddable-OpenSource/moddable/issues/251) but impossible, I discovered it's not.

IOU details, but this looks promising. The main impact is that test scripts should become modules (https://github.com/Agoric/agoric-sdk/issues/49 e.g. 8bf4116679d5)

Also: the `test-xs-manifest.json` and `test-xs-main.js` files are in the top `SwingSet` directory.

test-xs: 14/14 PASS from test-marshal
https://github.com/dckc/SwingSet/tree/xs-platform 40ee4a0

### Earlier approach

earlier status: 12 / 16 PASS - 4 FAIL. description:
https://github.com/dckc/SwingSet/tree/test-kernel-xs/test/test-kernel-xs 2784e5b

**Comment by dckc** [comment]
All 174 tests from test-marshal and test-kernel are passing with no change to the `src/` code and small tweaks to `test/` code.

https://github.com/Agoric/SwingSet/commit/643f37dd7c856f074ee24406be96cc6acfb4bf82
since rebased to 5e6c533f4b2d9f7df6439bfbe38d91e2497df881


Some dependencies are tweaked:

 - `npm link @agoric/harden` https://github.com/dckc/harden/tree/deepFreeze-xs 7dbc995
 - `npm link @agoric/eventual-send` https://github.com/dckc/eventual-send/tree/delay-weakmap-xs bd2be3f (merged)
 - `npm link @agoric/tape-xs`  https://github.com/dckc/tape-xs 038d62d

### Noteable changes

 - 0023bb2 2019-09-02 test-marshal: declare Promise.makeHandled dependency
 - 2f61a35 2019-09-02 turn test-marshal script into module
 - c0df6e7 2019-09-02 xs-platform work-alike for console.log
 - 3c82696 2019-09-02 xs platform work-alike for setImmediate etc.
 - 26b90d5 2019-09-02 test-xs: 14/14 PASS from test-marshal
 - 74eb464 2019-09-02 xs: push harden, eventual-send changes down
 - 4ed2437 2019-09-02 turn test-kernel into module
 - 495a7ee 2019-09-02 xs: add kernel subdirectories to manifest
 - 5e6c533 2019-09-02 xs: run test-kernel too (174 passing out of 174)


### Moddable SDK: Getting Started

Prerequisite to this work is [Host environment setup for linux](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20-%20Getting%20Started.md#host-linux) (or [for macOS](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20-%20Getting%20Started.md#host-mac)).

At this point, one can run the hello-world example along with the `xsb` debugger:

```
~/projects/moddable$ cd examples/helloworld/
~/projects/moddable/examples/helloworld$ mcconfig -d -m -p lin
~/projects/moddable/examples/helloworld$ # or: mcconfig -d -m -p mac
# xsc Resource.xsb
...
# ld mc.so
```

![xsb-hello](https://user-images.githubusercontent.com/150986/64910456-53e24e00-d6dc-11e9-8b19-3a21d082e13b.png)

See also:
  - Moddable-OpenSource/moddable#257 debugging xs with VS Code

**Comment by dckc** [comment]
Porting `src/controller.js` is a puzzle. Some options I'm considering...:

 - make work-alikes for `fs` and `path` and share all the Agoric loading / evaluating code
 - use xs platform ahead-of-time compilation style module loading / evaluating and `Compartment` constructor
 - a mix: deal with modules in source form at runtime, but use moddable's `eval` and `Compartment` constructor

**Comment by dckc** [comment]
thoughts on `src/build-source-bundle.js`...

### eventual send operator syntax

i.e. `acornInjectPlugins: [infixBang()]` (though `infixBang` is now a misnomer... IOU pointer to discussion of `target~.msg(Args)`)

Should I ask the moddable / xs guys about supporting that?
p.s. done: asked for advice on how to go about it:

 - [ ] https://github.com/Moddable-OpenSource/moddable/issues/261

### bundling

Getting Babel to run in xs would have various grungy issues, but moreover, do we really want that in the TCB?

I'd be surprised if xs has a runtime module loader... They have an example using `import()`, but it does't parse js at run time; it loads ahead-of-time compiled stuff.

A quick-n-dirty rollup work-alike shouldn't be too hard, if my understanding is correct... all the imports have to go at the top of the file and export has to be a top-level token.

p.s. @dtribble points out @michaelfig 's work on https://github.com/Agoric/transform-module , which looks like just the thing!

 - [ ] SES on xs https://github.com/Agoric/SES/issues/16
 - [ ] __dirname, fs access https://github.com/Agoric/agoric-sdk/issues/66
   - [ ] https://github.com/Agoric/agoric-sdk/issues/15 bundleSource is ambient authority
     - [ ] https://github.com/Agoric/agoric-sdk/pull/371

**Comment by dckc** [comment]
### test-controller: 26 / 32 PASS; 6 FAIL

so the total, with `test-marshal` and `test-kernel` is 199 / 205 PASS; 6 FAIL

All six failures are the `withSES === true` cases.

The current `withSES === true` takes the kernel source, loads it as a function, and then stringifies it again, an then uses `eval` to turn it back into a function inside an SES Realm. In xs, the string form of the kernel isn't handy when you load it as a function. Straightforward options are:
  - take the kernel source and eval it in an SES Realm, without loading it in the outer realm
  - just import the kernel module into an SES Realm

The `withSES === false` code just imports the kernel module. It imports it into the outer realm, so I should add a `new Compartment()` around it. I'd have more confidence in doing that right if we had a few tests that shows why the `withSES === false` case is insecure (#151). (Same applies for eventual send operator: Agoric/SwingSet#150)

If it's important, I should be able to finish up the SES stubs to get `withSES === true` to run, if we skip loading the kernel source code into the outer realm and just deal with it in string form until it gets `eval`ed in the SES realm.

I cheated and used ahead-of-time compilation for the vat code too. I aim to sync with @michaelfig on transform-module to address that.

Details of the test run:
https://gist.github.com/dckc/dc7e560bbb2b6b989653b62445f38acf

as noted above, it involves `npm link` in 2 or 3 cases.
It also involves a symlink, since the xs loader requires the `.js` extension:

```
~/projects/agoric/SwingSet$ ls -l test/vat-controller-1.js 
lrwxrwxrwx 1 connolly connolly 16 Sep  8 15:42 test/vat-controller-1.js -> vat-controller-1
```

### Changelog (edited)

 - a3668d8 2019-09-08 require(), require.resolve() KLUDGEs
 - ea55849 2019-09-08 __dirname KLUDGE
 - f730661 2019-09-08 path stubs: isAbsolute, resolve
 - 1a3adda 2019-09-08 fs shim: readdirSync, statSync
 - 5e831ab 2019-09-08 SES stub: throw
 - 705935e 2019-09-08 evaluate-options stub: default function
 - f0170f5 2019-09-08 manifest entries for controller modules
 - a3ee7f7 2019-09-08 require shim: preload @agoric/harden; filter user modules
 - 0192471 2019-09-08 test-controller: turn off SES in 'load empty' (WIP)
 - 586ce02 2019-09-08 noop module for making compartments

**Comment by dckc** [comment]
### module loading, xs platforms, and `fxFindModule`

While the xs js-level Component API seems to handle only ahead-of-time compiled modules, I see the moddable SDK makes it pretty straightforward to [define a platform](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Platforms.md) including a C level `fxFindModule` hook: "Finding modules can involve looking for various kinds of files, using a set of preferred locations, etc. But on microcontrollers, all modules modules are prepared".

I'm not sure `fxFindModule` would allow async module lookup, though.

 - [ ] https://github.com/Agoric/agoric-sdk/issues/57 struggling with import specifiers

**Comment by dckc** [comment]
## Struggling to reproduce my own results away from my desktop: 163 / 173 PASS

As noted above, at my desktop, I have 195/201 tests passing.  After remembering a couple more work-arounds below, I'm up to 163/173. If I run just one of the test modules at a time, I get:

 - `testMarshal`: 63/63
 - `testKernel`: 106/106
 - `testController`: 7/17

### linux platform crept into npm script

The `test-xs` script specified `-p lin`. On a mac, it should be `-p mac`.

 - 875ab0f split test-xs by platform

###  xs only recognizes files as javascript modules if they end in `.js`

work-around:

```
SwingSet/test$ ln -s vat-controller-1 vat-controller-1.js
```

(_IOU issue, docs, and/or fix_)

## failed to open directory

next challenge:

```
# bootstrap with SES
= loading config from basedir ./test/basedir-controller-2
.../projects/moddable/modules/files/file/mac/modFile.c (245) # Exception: Iterator: failed to open directory!
```

See https://github.com/Agoric/SwingSet/issues/180

## tape / harden integration

```
harden$ git diff
diff --git a/package.json b/package.json
index 4754ead..0ddb906 100644
--- a/package.json
+++ b/package.json
@@ -36,7 +36,6 @@
     "prettier": "1.16.4",
     "rollup": "^1.3.2",
     "rollup-plugin-node-resolve": "^4.0.1",
-    "@agoric/tape-xs": "^0.1.0",
     "tape": "^4.9.2"
   },
   "directories": {
```

```
harden$ ls -l package.json 
-rw-r--r--  1  1338 Oct 26 15:04 package.json
```

**Comment by dckc** [comment]
@warner did some xs in C work back in Dec 2018  https://github.com/agoric-labs/moddable/tree/warner-linux-cli ddf4a43

Since then, moddable seems to have made an independent git history.

I re-sync'd BW's work: https://github.com/Moddable-OpenSource/moddable/compare/public...dckc:ag-linux-cli 3346e1a

(what happened to my notes from last night??? oh: https://github.com/Agoric/SES/issues/16#issuecomment-557375740 )

**Comment by dckc** [comment]
I got the kernel working inside the little xs cli program.

I'm not sure where to put stuff yet, so for now, it's a gist:

https://gist.github.com/dckc/8b0655faa70226e741b8f09a938840f4

**Comment by dckc** [comment]
@warner  you asked how SES-like xs is. I think https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/preload.md#automatic-freezing-of-built-ins is the answer. Is there some place (else) I should document it?

**Comment by dckc** [comment]
## ag-solo builds a withSES=true kernel, starts to load devices

it trips over `import ...` in device source. Gotta bundle those up.

At least this much is checked in...

https://github.com/dckc/cosmic-swingset/tree/xs-platform 5f07a15
https://github.com/dckc/moddable/tree/ag-linux-cli 1c04cb8
https://github.com/dckc/SwingSet/tree/xs-platform 6479fde

**Comment by dckc** [comment]
## ag-solo runs thru `run() done.`; does it work?

@warner @dtribble How close is this to working?

https://gist.github.com/dckc/dee8ca7e527e018bd3d03ec5e540bbbd

cosmic-swingset: 1ea6a96
SwingSet: 616104c
moddable: 1539a49
https://github.com/dckc/bundle-source/tree/allow-ocap 7946ff3
moddable 1539a492

and perhaps a few other local kludges. (in particular, all the vats and devices are rollup'd with filename conventions)
